# Generated by Django 5.2.4 on 2025-08-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_post/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.post')),
            ],
        ),
    ]
