# Generated by Django 5.2.4 on 2025-08-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='multimedia',
        ),
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_post/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='blog.post')),
            ],
        ),
    ]
